springdoc:
  swagger-ui:
    urls:
      - name: Employee Service
        url: /public/v3/api-docs/employee
      - name: Auth Service
        url: /public/v3/api-docs/auth

spring:
  application:
    name: api-gateway
  security:
    user:
      name: admin
      password: admin
      roles: ADMIN
  cloud:
    gateway:
      globalcors:
        corsConfigurations:
          '[/**]':
            allowedOrigins:
              - ${CORS_ALLOWED_ORIGIN:http://localhost:4200}
              - ${services.api-gateway.url}
            allowedMethods:
              - GET
              - POST
              - PUT
              - DELETE
              - OPTIONS
            allowedHeaders:
              - "*"
            allowCredentials: true
      default-filters:
        - TokenRelay
      routes:
        - id: auth-service
          uri: ${AUTH_SERVICE_URL:http://localhost:8081}
          predicates:
            - Path=/auth-service/**
          filters:
            - RewritePath=/auth-service/(?<segment>.*), /${segment}
        - id: employee-service
          uri: ${EMPLOYEE_SERVICE_URL:http://localhost:8082}
          predicates:
            - Path=/employee-service/**
          filters:
            - RewritePath=/employee-service/(?<segment>.*), /${segment}
            - TokenRelay
            - name: CircuitBreaker
              args:
                name: employeeCircuitBreaker
                fallbackUri: forward:/fallback
        - id: auth-service-swagger
          uri: ${AUTH_SERVICE_URL:http://localhost:8081}
          predicates:
            - Path=/public/v3/api-docs/auth
          filters:
            - SetPath=/v3/api-docs
        - id: employee-service-swagger
          uri: ${EMPLOYEE_SERVICE_URL:http://localhost:8082}
          predicates:
            - Path=/public/v3/api-docs/employee
          filters:
            - SetPath=/v3/api-docs
        # - id: employee-service-swagger
        #   uri: ${EMPLOYEE_SERVICE_URL:http://localhost:8082}
        #   predicates:
        #     - Path=/public/swagger-ui/**, /public/v3/api-docs/**
        #   filters:
        #     - RewritePath=/public/(?<segment>.*), /${segment}
        # - id: swagger-config
        #   uri: ${EMPLOYEE_SERVICE_URL:http://localhost:8082}
        #   predicates:
        #     - Path=/public/v3/api-docs/swagger-config
        #   filters:
        #     - RewritePath=/public/(?<segment>.*), /${segment}

resilience4j:
  circuitbreaker:
    instances:
      employeeCircuitBreaker:
        registerHealthIndicator: true
        slidingWindowSize: 5
        failureRateThreshold: 50
        waitDurationInOpenState: 5s
