server:
  port: ${API_GATEWAY_PORT:8080}

springdoc:
  swagger-ui:
    path: /
    urls:
      - name: Employee Service
        url: /api-docs/employee-service
      - name: Auth Service
        url: /api-docs/auth-service

spring:
  application:
    name: api-gateway
  cloud:
    gateway:
      default-filters:
        - TokenRelay
      routes:
        - id: auth-service
          uri: lb://auth-service
          predicates:
            - Path=/auth/**

        - id: employee-service
          uri: lb://employee-service
          predicates:
            - Path=/api/v1/**
          filters:
            - TokenRelay
            - name: CircuitBreaker
              args:
                name: employeeCircuitBreaker
                fallbackUri: forward:/fallback
        - id: employee-service-swagger
          uri: lb://employee-service
          predicates:
            - Path=/api-docs/employee-service
          filters:
            - RewritePath=/api-docs/employee-service, /v3/api-docs
        - id: auth-service-swagger
          uri: lb://auth-service
          predicates:
            - Path=/api-docs/auth-service
          filters:
            - RewritePath=/api-docs/auth-service, /v3/api-docs

resilience4j:
  circuitbreaker:
    instances:
      employeeCircuitBreaker:
        registerHealthIndicator: true
        slidingWindowSize: 5
        failureRateThreshold: 50
        waitDurationInOpenState: 5s
