server:
  port: ${services.api-gateway.port}

services:
  api-gateway:
    port: 8080
  auth-service:
    port: 8081
  employee-service:
    port: 8082

springdoc:
  swagger-ui:
    urls:
      - name: Employee Service
        url: /api-docs/employee-service
      - name: Auth Service
        url: /api-docs/auth-service

spring:
  application:
    name: api-gateway

  cloud:
    gateway:
      # globalcors:
      #   corsConfigurations:
      #     '[/**]':
      #        allowedOrigins:
      #          - "http://localhost:4200"
      #          - "http://37.60.230.21:8080"
      #        allowedMethods:
      #          - GET
      #          - POST
      #          - PATCH
      #          - PUT
      #          - DELETE
      #          - OPTIONS
      #        allowedHeaders:
      #          - "*"
      #        allowCredentials: true
      default-filters:
        - TokenRelay
      routes:
        - id: auth-service
          uri: lb://auth-service
          predicates:
            - Path=/auth/**
          # filters:
          #   - RewritePath=/auth-service/(?<segment>.*), /${segment}

        - id: employee-service
          uri: lb://employee-service
          predicates:
            - Path=/api/v1/**
          filters:
            # - RewritePath=/employee-service/(?<segment>.*), /${segment}
            - TokenRelay
            # - PreserveHostHeader
            - name: CircuitBreaker
              args:
                name: employeeCircuitBreaker
                fallbackUri: forward:/fallback
        - id: employee-service-swagger
          uri: lb://employee-service
          predicates:
            - Path=/api-docs/employee-service
          filters:
            - RewritePath=/api-docs/employee-service, /v3/api-docs
        - id: auth-service-swagger
          uri: lb://auth-service
          predicates:
            - Path=/api-docs/auth-service
          filters:
            - RewritePath=/api-docs/auth-service, /v3/api-docs
            # - PreserveHostHeader

        
resilience4j:
  circuitbreaker:
    instances:
      employeeCircuitBreaker:
        registerHealthIndicator: true
        slidingWindowSize: 5
        failureRateThreshold: 50
        waitDurationInOpenState: 5s

# logging:
#   level:
#     org.springframework.security: DEBUG
#     org.springframework.cloud.gateway: DEBUG
