server:
  port: 8080

springdoc:
  swagger-ui:
    urls:
      - name: employee-service
        url: /public/v3/api-docs/employee


spring:
  application:
    name: api-gateway
  security:
    user:
      name: admin
      password: admin
      roles: ADMIN
  cloud:
    gateway:
      default-filters:
        - TokenRelay
      routes:
        - id: employee-service
          uri: lb://employee-service
          predicates:
            - Path=/employee-service/**, /public/swagger-ui/**, /public/v3/api-docs/**
          filters:
            - RewritePath=/employee-service/(?<segment>.*), /${segment}
            - name: CircuitBreaker
              args:
                name: employeeCircuitBreaker
                fallbackUri: forward:/fallback
    security:
      oauth2:
        client:
          registration:
            keycloak:
              client-id: spring-gateway
              client-secret: your-secret
              authorization-grant-type: authorization_code
              redirect-uri: "{baseUrl}/login/oauth2/code/{registrationId}"
              scope: openid
          provider:
            keycloak:
              issuer-uri: http://localhost:8180/realms/myrealm

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:8761/eureka/

resilience4j:
  circuitbreaker:
    instances:
      employeeCircuitBreaker:
        registerHealthIndicator: true
        slidingWindowSize: 5
        failureRateThreshold: 50
        waitDurationInOpenState: 5s
