services:
  eureka-server:
    port: 8761
  api-gateway:
    port: 8080
  auth-service:
    port: 8081
  employee-service:
    port: 8082
  
eureka:
  client:
    service-url:
      default-zone: http://localhost:8761/eureka/
  instance:
    prefer-ip-address: true
    
spring:
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://localhost:8180/realms/myrealm
