services:
  eureka-server:
    port: 8761
  api-gateway:
    port: 8080
  keycloak:
    port: 8180
  auth-service:
    port: 8081
  employee-service:
    port: 8082

employee-service:
  token: Bearer service-token-12345-secret
auth-service:
  token: Bearer service-token-12345-secret
  
eureka:
  client:
    service-url:
      default-zone: http://localhost:${services.eureka-server.port}/eureka/
  instance:
    prefer-ip-address: true
    
spring:
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://localhost:${services.keycloak.port}/realms/myrealm
