spring:
  datasource:
    url: jdbc:postgresql://dpg-d21nn9qdbo4c73edgsjg-a:5432/auth_database
    username: postgres_data_ls95_user
    password: Lyz23xy8wXF7mgADQhsJfW9a6gQoY7YO
    driver-class-name: org.postgresql.Driver
