server:
  port: ${services.auth-service.port}

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/auth_database
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver
        
keycloak:
  token-uri: http://localhost:${services.keycloak.port}/realms/myrealm/protocol/openid-connect/token
  client-id: spring-gateway
  client-secret: d2xgUFAfbJzCKu9ztbz7q5AtkwUZvRuf
