server:
  port: ${services.auth-service.port}

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/auth_database
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver
        
keycloak:
  server-uri: http://localhost:${services.keycloak.port}
  token-uri: http://localhost:${services.keycloak.port}/realms/myrealm/protocol/openid-connect/token
  realm: myrealm
  client-id: spring-gateway
  client-secret: SiZ1oOLaSgnu3KEWbqb2FeqAyQV8rkBg
  username: admin
  password: admin
