springdoc:
  swagger-ui:
    path: /

spring:
  datasource:
  jpa:
    hibernate:
      ddl-auto: create
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.PostgreSQLDialect
    url: jdbc:postgresql://localhost:5432/employee_database
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver

server:
  port: ${services.employee-service.port}
  
management:
  endpoints:
    web:
      exposure:
        include: "*"
